name: Docker Image CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize]

jobs:
  Cancel_previous_workflow_runs:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  Build:
    runs-on: ubuntu-22.04
    permissions: 
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Notify Discord
        if: github.event_name == 'push'
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD }}
          message: 'New commit pushed to main branch-${{ github.action_status }}'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: format code
        run: npm run format

  # Docker:
  #   needs: Build
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: ./Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

      - name: Login to Amazon ECR
        run: |
         aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 767397723821.dkr.ecr.us-east-2.amazonaws.com
      - name: Build Docker image
        run: |
          docker build -t gateway-repository .  
      
      - name: Tag Docker image
        run: |
          docker tag gateway-repository:latest 767397723821.dkr.ecr.us-east-2.amazonaws.com/gateway-repository:latest
          
      - name: Push Docker image to ECR
        run: |
          docker push 767397723821.dkr.ecr.us-east-2.amazonaws.com/gateway-repository:latest
  Deploy_AWS:
    runs-on: ubuntu-22.04
   
    steps:
      - name: Deploy to production AWS ECR
        if: github.event_name == 'push'
        run: echo "Deploying to production"
