name: Docker Image CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize]

jobs:
  Cancel_previous_workflow_runs:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Notify Discord
        if: github.event_name == 'push'
        uses: discord-actions/message@v2
        with:
           webhookUrl: ${{ secrets.DISCORD }}
           message: ${{github.action_status}}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: format code
        run: npm run format
  Docker:
    needs: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Dokcer Login
        uses: actions/checkout@v4
  Deploy:
    runs-on: ubuntu-22.04
    needs: [Docker]
    steps:
      - name: Deploy to production
        if: github.event_name == 'push'
        run: echo "Deploying to production"
