name: Dock

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize]

jobs:
  Cancel_previous_runs:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  Build:
    runs-on: ubuntu-22.04
    needs: Cancel_previous_runs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: format code
        run: npm run format

  Deploy:
    runs-on: ubuntu-22.04
    needs: Build
    steps:
      - name: Deploy to production
        if: github.event_name == 'push'
        run: echo "Deploying to production"
