name: Devolepment CI/CD
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
  
    
  push:
    branches:
      - develop
jobs:
  Build:
    permissions:
      contents: read
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        
        node-version: [22]
    environment:
      name: Develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install
          npm uninstall inflight
          npm install -g npm@latest

      - name: Build
        run: npm run build

