name: Devolepment CI/CD
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened]
    branches:
      - develop
jobs:
  Build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
      - name: Install Dependencies
        run: |
          npm install
          npm install -g npm@latest
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4

      - name: Build
        run: npm run build

  # Docker:
  #     runs-on: ubuntu-22.04
  #     needs: Build
  #     steps:
  #        - name: Login to ECR
  #          uses: docker/login-action@v3
  #          with:
  #           registry: <aws-account-number>.dkr.ecr.<region>.amazonaws.com
  #           username: ${{ vars.AWS_ACCESS_KEY_ID }}
  #           password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
