name: Devolepment CI/CD
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  Build:
    permissions:
      id-token: write
      contents: read
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node-version: [22]
    environment:
      name: Develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: npm run build

  Docker:
    runs-on: ubuntu-22.04
    environment:
      name: Develop
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Build to image
        if: github.event_name == 'pull_request'
        run: |
          docker build -t dev-transcriber .
          docker save -o dev-transcriber.tar dev-transcriber

      - name: upload artifact to s3
        if: github.event_name == 'pull_request'
        run: |
          aws s3 cp dev-transcriber.tar s3://bukect-artifact-dev-transcriber/

  Deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-22.04
    needs: [Build, Docker]
    environment:
      name: Develop
    steps:
      - name: Download artifact from s3
        run: |
          aws s3 cp s3://bukect-artifact-dev-transcriber/dev-transcriber.tar ./dev-transcriber.tar

      - name: Load Docker image
        run: |
          docker load -i ./dev-transcriber.tar

      - name: Login to AWS ECR
        uses: docker/login-action@v3
        with:
          registry: 767397723821.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.DEV_AWS_ACCESS_KEY_ID}}
          password: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Image to AWS ECR
        run: |
          docker tag dev-transcriber:latest 767397723821.dkr.ecr.us-east-2.amazonaws.com/dev-transcriber:${{github.sha}}
          docker push 767397723821.dkr.ecr.us-east-2.amazonaws.com/dev-transcriber:${{github.sha}}
