name: Devolepment CI/CD
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  Build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    environment:
      name: Develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
      - name: Install Dependencies
        run: |
          npm install
          npm uninstall inflight
          npm install -g npm@latest

      - name: Build
        run: npm run build

  Docker:
    needs: Build
    runs-on: ubuntu-22.04
    environment: 
      name: Develop
    env:
      AWS_USERNAME: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_PASSWORD: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 767397723821.dkr.ecr.us-east-2.amazonaws.com/dev-transcriber
          username: ${{env.AWS_USERNAME}}
          password: ${{env.AWS_PASSWORD}}

      - name: Build and Push Docker Image 
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true

          tags: dev-transcriber:latest 767397723821.dkr.ecr.us-east-2.amazonaws.com/dev-transcriber:latest