name: Devolepment CI/CD
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
  


  push:
    branches:
      - develop

jobs:
  Build:
    permissions:
      id-token: write
      contents: read
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        node-version: [22]
    environment:
      name: Develop

    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install
          npm install -g npm@latest

      - name: Build
        run: npm run build

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{secrets.DEV_AZURE_CLIENT_ID}}
          subscription-id: ${{secrets.DEV_AZURE_SUBSCRIPTION_ID}}
          tenant-id: ${{secrets.DEV_AZURE_TENANT_ID}}
          environment: Develop
          audience: api://AzureADTokenExchange
          

