name: Check CI/CD
on:

  push: 
    branches: 
      - feature/*
jobs:
  Build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
      - name: Install Dependencies
        run: |
          npm install
          npm install -g npm@latest
      - name: Build
        run: npm run build

  Docker:
    environment: 
      name: Develop 
    runs-on: ubuntu-22.04
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 767397723821.dkr.ecr.us-east-2.amazonaws.com
      - name: Build to image
        run: |
         docker build -t dev-transcriber . 
      - name: Tag image
        run: |
         docker tag dev-transcriber:latest 767397723821.dkr.ecr.us-east-2.amazonaws.com/dev-transcriber:latest 
      - name: Push image
        run: docker push 767397723821.dkr.ecr.us-east-2.amazonaws.com/dev-transcriber:latest
