name: Devolepment CI/CD
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
  
    
  push:
    branches:
      - develop
jobs:
  Build:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16,20,22]
    environment:
      name: Develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{matrix.node-version}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
      - name: Install Dependencies
        run: |
          npm install
          npm uninstall inflight
          npm install -g npm@latest

      - name: Build
        run: npm run build

